- name: get configprofiles data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    config_profile_name: "{{ config_profile_name }}"
    endpoint: "{{ endpoint}}"
    restart: "{{ restart }}"
    lxca_action: "{{ lxca_action }}"
    powerdown: "{{ powerdown }}"
    resetimm: "{{ resetimm }}"
    force: "{{ force }}"
    command_options: configprofiles
  register: rslt
  tags:
     configprofiles