- name: get configstatus data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    endpoint: "{{ endpoint }}"
    status: "{{ status }}"
    command_options: get_configstatus
  register: rslt
  tags:
    get_configstatus
