- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    includeSettings: "{{ includeSettings }}"
    command_options: get_particular_configpattern
  register: rslt
  tags:
     get_particular_configpattern