- block:
  - name: Get Jobid for import file to management server
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      lxca_action: "{{ lxca_action }}"
      files: "{{ files }}"
      command_options: import_managementserver_pkg
    register: rslt

  - debug:
      var: rslt.result.jobid

  - name: Post Job for import files to mamagement server
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      lxca_action: "{{ lxca_action }}"
      files: "{{ files }}"
      jobid: "{{ rslt.result.jobid }}"
      command_options: import_managementserver_pkg
    register: rslt
  tags:
    import_managementserver_pkg
