- block:
  - name: Get Jobid for import file to repository of osimages
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      osimages_dict: "{{ osimages_imagetype_dict }}"
      command_options: osimages
    register: rslt

  - debug:
      var: rslt.result.jobId

  - name: Check import_dict value
    set_fact:
     mod_import_dict: "{{ import_dict | combine( {'jobId' : rslt.result.jobId }) }}"

  - name: Post Job for import file to repository of osimages
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      osimages_dict: "{{ mod_import_dict }}"
      command_options: osimages
    register: rslt
  tags:
    import_osimages