---
# tasks file for lenovo.lxca-config
- import_tasks: updatepolicy.yml
- import_tasks: query_update_comp.yml
- import_tasks: query_update_status.yml
- import_tasks: update_firmware_all.yml
- import_tasks: import_configpatterns.yml
- import_tasks: apply_configpatterns.yml
- import_tasks: get_configpatterns.yml
- import_tasks: get_particular_configpattern.yml
- import_tasks: get_configstatus.yml
- import_tasks: configprofiles.yml
- import_tasks: configtargets.yml
- import_tasks: manage.yml
- import_tasks: unmanage.yml
- import_tasks: updaterepo.yml
- import_tasks: update_firmware.yml
- import_tasks: updatepolicy.yml
- import_tasks: osimages.yml
- import_tasks: import_osimages.yml
- import_tasks: import_managementserver_pkg.yml
- import_tasks: get_managementserver_pkg.yml
- import_tasks: get_particular_managementserver_pkg.yml
- import_tasks: update_managementserver_pkg.yml
