- name: Get or Apply osimages to device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    osimages_info: "{{ osimages_info }}"
    osimages_dict: "{{ osimages_dict }}"
    command_options: osimages
  register: rslt
  tags:
     osimages