- name: Getting Firmware Update Status from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: update_firmware_query_status
  register: rslt
  tags:
     query_update_status