- name: get all stored credentials from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: get_storedcredentials
  register: rslt
  tags:
     get_all_storedcredentials


- name: get particular stored credentials from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    storedcredential_id: "{{ storedcredential_id }}"
    command_options: get_storedcredentials
  register: rslt
  tags:
     get_particular_storedcredentials

- name: create stored credentials on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    user: "{{ user }}"
    password: "{{ password }}"
    description: "{{ description }}"
    command_options: create_storedcredentials
  register: rslt
  tags:
     create_storedcredentials

- name: Update stored credentials on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    storedcredential_id: "{{ storedcredential_id }}"
    user: "{{ user }}"
    password: "{{ password }}"
    description: "{{ description }}"
    command_options: update_storedcredentials
  register: rslt
  tags:
     update_storedcredentials

- name: delete particular storedcred credentials from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    storedcredential_id: "{{ storedcredential_id }}"
    command_options: delete_storedcredentials
  register: rslt
  tags:
     delete_particular_storedcredentials