- block:
  - name: Unmanaging given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      force: "{{ force }}"
      command_options: unmanage
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check submission of Unmanage job
    assert:
      that:
        - " 'Success' in rslt_job.msg"

  - name: Polling for Status of UnManage Operation
    pylxca_module:
      command_options: unmanage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 20
    delay: 15

  - debug:
      var: result.result.progress
  tags:
    unmanage
