- name: Updating Firmware of device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    mode: "{{ mode}}"
    lxca_action: "{{ lxca_action }}"
    cmm: "{{ cmm }}"
    switch: "{{ switch }}"
    server: "{{ server }}"
    storage: "{{ storage }}"
    command_options: update_firmware
  register: rslt
  tags:
     update_firmware
