- name: Get or Apply updatepolicy to device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    policy_info: "{{ policy_info}}"
    policy_name: "{{ policy_name}}"
    policy_type: "{{ policy_type}}"
    uuid: "{{ uuid }}"
    jobid: "{{ jobid }}"
    command_options: updatepolicy
  register: rslt
  tags:
    updatepolicy