{
  'template_type':'SystemInfo',
  'template':{
    'contact':'contact',
    'description':'Pattern created by test API ',
    'location':'location',
    'name':'Learned-System_Info-99',
    'systemName':{
      'autogen':'Disable',
      'hyphenChecked':False},
    'type':'SystemInfo',
    'uri':'\/config\/template\/61',
    'userDefined':True}
}